# Customer Segmentation and Retention Analysis

## Running for the first time

Run this to download the .zip file.
```
import urllib.request

url = (
    "https://archive.ics.uci.edu/static/public/502/"
    "online+retail+ii.zip"
)

urllib.request.urlretrieve(url, "online_retail_ii.zip")

```

Import the following to unzip the file.

```
import zipfile

with zipfile.ZipFile("online_retail_ii.zip", "r") as zip_ref:
    zip_ref.extractall("data")

```

You may install the following dependencies
```
pip install pandas openpyxl jupyter
```

## Data Loading

Now, since we have our data, we load it as follows:

In [1]:
import pandas as pd

df1 = pd.read_excel("data/online_retail_II.xlsx", sheet_name="Year 2009-2010")
df2 = pd.read_excel("data/online_retail_II.xlsx", sheet_name="Year 2010-2011")

In [2]:
df1.shape, df2.shape

((525461, 8), (541910, 8))

Now, we join the datasets together.

In [16]:
df = pd.concat([df1, df2])

In [17]:
df = df.reset_index(drop=True)
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [25]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [10]:
df

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [26]:
df.columns

Index(['invoice', 'stockcode', 'description', 'quantity', 'invoicedate',
       'price', 'customer_id', 'country'],
      dtype='str')

In [18]:
df.shape

(1067371, 8)

Next, we standardise the entries of the above dataframe.

In [11]:
df.dtypes

invoice                object
stockcode              object
description            object
quantity                int64
invoicedate    datetime64[us]
price                 float64
customer_id           float64
country                   str
dtype: object

In [12]:
df['country'].unique()

<StringArray>
[      'United Kingdom',               'France',                  'USA',
              'Belgium',            'Australia',                 'EIRE',
              'Germany',             'Portugal',                'Japan',
              'Denmark',              'Nigeria',          'Netherlands',
               'Poland',                'Spain',      'Channel Islands',
                'Italy',               'Cyprus',               'Greece',
               'Norway',              'Austria',               'Sweden',
 'United Arab Emirates',              'Finland',          'Switzerland',
          'Unspecified',                'Malta',              'Bahrain',
                  'RSA',              'Bermuda',            'Hong Kong',
            'Singapore',             'Thailand',               'Israel',
            'Lithuania',          'West Indies',              'Lebanon',
                'Korea',               'Brazil',               'Canada',
              'Iceland',         'Saudi Arabia',       'Czech Republic',
   'European Community']
Length: 43, dtype: str

Basic information

In [14]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   invoice      1067371 non-null  object
 1   stockcode    1067371 non-null  object
 2   description  1062989 non-null  object
 3   quantity     1067371 non-null  int64
 4   invoicedate  1067371 non-null  datetime64[us]
 5   price        1067371 non-null  float64
 6   customer_id  824364 non-null   float64
 7   country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 65.1+ MB
None

Next, we check for missing values in each columns.

In [15]:
print(df.isnull().sum())

invoice             0
stockcode           0
description      4382
quantity            0
invoicedate         0
price               0
customer_id    243007
country             0
dtype: int64

In [27]:
for col in df.columns:
    print(col)
    print(f"The first 5 elements of the {col} column are {df[col].unique()[:5]}")
    print(f"The {col} column has {df[col].nunique()} unique entries")
    print()

invoice
The first 5 elements of the invoice column are [489434 489435 489436 489437 489438]
The invoice column has 53628 unique entries

stockcode
The first 5 elements of the stockcode column are [85048 '79323P' '79323W' 22041 21232]
The stockcode column has 5305 unique entries

description
The first 5 elements of the description column are ['15CM CHRISTMAS GLASS BALL 20 LIGHTS' 'PINK CHERRY LIGHTS'
 ' WHITE CHERRY LIGHTS' 'RECORD FRAME 7" SINGLE SIZE '
 'STRAWBERRY CERAMIC TRINKET BOX']
The description column has 5698 unique entries

quantity
The first 5 elements of the quantity column are [12 48 24 10 18]
The quantity column has 1057 unique entries

invoicedate
The first 5 elements of the invoicedate column are <DatetimeArray>
['2009-12-01 07:45:00', '2009-12-01 07:46:00', '2009-12-01 09:06:00',
 '2009-12-01 09:08:00', '2009-12-01 09:24:00']
Length: 5, dtype: datetime64[us]
The invoicedate column has 47635 unique entries

price
The first 5 elements of the price column are [6.95 6.75 2.1  1.25 1.65]
The price column has 2807 unique entries

customer_id
The first 5 elements of the customer_id column are [13085. 13078. 15362. 18102. 12682.]
The customer_id column has 5942 unique entries

country
The first 5 elements of the country column are <StringArray>
['United Kingdom', 'France', 'USA', 'Belgium', 'Australia']
Length: 5, dtype: str
The country column has 43 unique entries